packages:
  - "crates/*"
  - "packages/*"
  - "examples/*"
allowBuilds:
  '0': esbuild
  '1': sharp
  '2': unrs-resolver
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@morph-css/kit@0.4.2 || 0.4.3'
  - '@morph-css/node@0.4.3'
