import fs from "fs";
import path from "path";
import { MorphCompiler } from "@morph-css/node";
import type { Plugin, PluginOption, ViteDevServer, ResolvedConfig } from "vite";
import { MorphCSSOptions, defaultOptions } from "./options";

export type { MorphCSSOptions };

export default function morphcssPlugin(
  userOptions: Partial<MorphCSSOptions> = {},
): PluginOption[] {
  const options = {
    ...defaultOptions,
    ...userOptions,
  };

  let compiler: MorphCompiler | null = null;
  let server: ViteDevServer | null = null;
  let config: ResolvedConfig | null = null;

  let currentCssHash = "";
  let utilitiesLoaded = false;
  
  const outputPath = path.resolve(process.cwd(), options.output);

  function ensureCompiler() {
    if (!compiler) {
      compiler = new MorphCompiler();
    }
    return compiler;
  }

  function loadUtilities() {
    if (utilitiesLoaded) return;
    utilitiesLoaded = true;

    const utilities = Array.isArray(options.utilities)
      ? options.utilities
      : options.utilities
        ? [options.utilities]
        : [];

    for (const file of utilities) {
      try {
        const resolved = path.resolve(process.cwd(), file);
        const css = fs.readFileSync(resolved, "utf8");
        ensureCompiler().ingestCss(css);
        console.log(`[MorphCSS] utility loaded: ${file}`);
      } catch (err) {
        console.error(`[MorphCSS] failed loading utility ${file}`, err);
      }
    }
  }

  function writeCssFile() {
    const rawCss = ensureCompiler().generateCss();
    const header = "/* \n * This file is automatically generated by MorphCSS.\n * Do not edit it directly.\n */\n\n";
    const css = header + rawCss;
    
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(outputPath, css, "utf8");
  }

  function shouldTransform(id: string) {
    if (!/\.[jt]sx?$/.test(id)) return false;
    if (id.endsWith(".d.ts")) return false;
    if (id.includes("node_modules")) return false;
    if (id.includes("/dist/")) return false;
    if (id.startsWith("\0")) return false;
    return true;
  }

  const corePlugin: Plugin = {
    name: "vite-plugin-morphcss",
    enforce: "pre",

    configResolved(resolvedConfig) {
      config = resolvedConfig;
      compiler = new MorphCompiler();
      
      // We still load static files if they exist physically, but dynamic ones will be caught by the ingest plugin
      loadUtilities();
    },

    buildStart() {
      writeCssFile();
    },

    configureServer(devServer) {
      server = devServer;
    },

    transform(code, id) {
      if (!shouldTransform(id)) return null;

      const prevHash = currentCssHash;
      const result = ensureCompiler().compile(code, id);
      const newHash = ensureCompiler().generateCssHash();

      if (newHash !== prevHash) {
        currentCssHash = newHash;
        writeCssFile();
      }

      return {
        code: result.code,
        map: null,
      };
    },

    async handleHotUpdate(ctx) {
      if (!compiler) return;

      const file = ctx.file;

      if (shouldTransform(file)) {
        compiler.invalidate(file);
      }

      const hash = compiler.generateCssHash();
      if (hash !== currentCssHash) {
        currentCssHash = hash;
        writeCssFile();
      }
    },

    generateBundle(_, bundle) {
      if (config?.command !== "build") return;

      const generatedCss = ensureCompiler().generateCss();
      if (!generatedCss.trim()) return;

      for (const [fileName, chunk] of Object.entries(bundle)) {
        if (
          chunk.type === "asset" &&
          fileName.endsWith(".css") &&
          typeof chunk.source === "string"
        ) {
          chunk.source += "\n" + generatedCss;
        }
      }
    },
  };

  const ingestPlugin: Plugin = {
    name: "vite-plugin-morphcss-ingest",
    transform(code, id) {
      if (!id.endsWith(".css") || id.includes(".morphcss")) return null;

      const utilities = Array.isArray(options.utilities)
        ? options.utilities
        : options.utilities
          ? [options.utilities]
          : [];

      // Check if this CSS file is marked as a utility
      const isUtility = utilities.some((u) => id.includes(u.replace("./", "")));
      
      if (isUtility) {
        console.log(`[MorphCSS] Intercepted compiled utility: ${id}`);
        console.log(`[MorphCSS] First 100 chars: ${code.slice(0, 100)}`);
        // ensureCompiler().ingestCss(code);
      }
      return null;
    },
  };

  return [corePlugin, ingestPlugin];
}