/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MorphCompiler {
  constructor()
  compile(source: string, filename: string): CompileResult
  ingestCss(css: string): void
  generateCss(): string
  generateCssHash(): string
  invalidate(filename: string): void
}

export interface CompileResult {
  code: string
}
